version: "3.9"

services:
  dockertest: 
    image: node
    container_name: proyectnode
    ports:
      - 5000:3000
    build: .
    command: node server.js
  db: 
    image: mongo
    container_name: mymongo
    ports:
      - 27017:27017
